name: Manual Workflow


on:
  workflow_dispatch:
    inputs:
      name:
        description: 'NAME'
        type: string
        default: 'test'
      age:
        description: 'AGE'
        type: number
        required: true
        
  

jobs:
  Manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{inputs.name}}"

      - name: Age
        run: echo "${{inputs.age}}"
    

 
      
