name: Manual Workflow


on:
  workflow_dispatch:
    inputs:
      name:
        description: 'NAME'
        type: string
        default: 'test'
      age:
        description: 'AGE'
        type: number
        required: true
      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female
        
  

jobs:
  Manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{inputs.name}}"

      - name: Age
        run: echo "${{inputs.age}}"

      - name: Gender
        run: echo "${{inputs.gender}}"
    

 
      
